services:
  soda_ansible:
    image: alpine/ansible
    container_name: soda_ansible
    restart: on-failure:5
    logging:
      driver: 'json-file'
      options:
        max-size: '50m'
    volumes:
      - ./:/app
    working_dir: /app
    command: sleep infinity
