all:
  hosts:
    jump_server:
      ansible_host: ip.server.net
      ansible_user: ec2-user
      ansible_ssh_private_key_file: /app/ssh/ssh.pem
      ansible_port: 22

    soda_server:
      ansible_host: ip.server2.net
      ansible_user: ec2-user
      ansible_ssh_private_key_file: /app/ssh/ssh.pem
      ansible_port: 22
      ansible_ssh_common_args: "-o ProxyCommand='ssh -W %h:%p userProxy@host.proxy -i /app/ssh/ssh.pem'"
